### ISSUE TITLE
Create project for each exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#309]
To help users get started programming, we should provide the user with a skeleton .fsproj file. This .fsproj file should work with the .NET CLI and run on .NET Core.

**Comment by hobbitjoe** [comment]
@ErikSchierboom some coworkers and I have been using visual studio code along with a make file using Fake in order to build the code and run the tests without the need of a fsproj file.  Since we do not use a fsproj file it looks like the test file has errors highlighted incorrectly.  Not sure if you would be interested in something like this or not, but figured I'd let you know how I've been running the f# tests.

**Comment by ErikSchierboom** [comment]
@hobbitjoe Cool. The [build script](https://github.com/exercism/xfsharp/blob/master/build.fsx) does something similar. With the .NET CLI tooling (and updated .fsproj files) almost being finished, I think we won't be needing such a FAKE script (hopefully). Would you mind if I contact you to test things once I'll be working on this issue?

**Comment by hobbitjoe** [comment]
@ErikSchierboom sure, I'll be happy to help test!

**Comment by ErikSchierboom** [comment]
Great! I'll keep you to that promise :)

**Comment by ErikSchierboom** [comment]
Fixed by #348. @hobbitjoe Would you mind testing it (by fetching a new exercise) to see if it works?

**Comment by hobbitjoe** [comment]
@ErikSchierboom sorry for the delay but I was able to fetch a new problem today and test it out.  I was able to run the tests via the CLI using dotnet core 2.0 on macOS 10.12.6 with no issues.  Let me know if any other information is needed.

**Comment by ErikSchierboom** [comment]
@hobbitjoe Great! Thanks for testing.
