### ISSUE TITLE
What was it like to learn F#?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp#738]
We’ve recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.

As a first step, we’ll be [examining the ways in which languages are unique and the ways in which they are similar](https://github.com/exercism/exercism/issues/5059). For this, we’d really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:

1. How was your experience learning F#? What was helpful while learning F#? What did you struggle with? How did you tackle problems?
1. In what ways did F# differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Could you spare 5 minutes to help us by answering these questions? It would greatly help us improve the experience students have learning F# :)

_Note: this issue is **not** meant as a discussion, just as a place for people to post their own, personal experiences._

_Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io_

Thank you!

**Comment by ErikSchierboom** [comment]
> How was your experience learning F#?

I started learning F# to combine my love for the .NET platform and my new-found love for functional programming. When I started learning F#, I was quite familiar with the .NET platform. I also knew two functional languages: Scala and Haskell, of which the former conceptually was quite similar to F# (it also supported non-functional programming). Having learnt Scala and Haskell made the transition to F# relatively easy. Already knowing the .NET platform also greatly helped, as I could use the same IDE (Visual Studio) I was using to programming C# in, as well as already knowing the API's that were available in the .NET platform.

> What was helpful while learning F#?

When learning Haskell, [Learn You a Haskell for Great Good!](http://learnyouahaskell.com/chapters) was a great resource. I thus started to search for a similar resource when learning F# and was stunned to find an even better resource for F#: [F# for fun and profit](https://fsharpforfunandprofit.com/). Not only did it teach F# (very) well, it also taught about why you should use F# and some of the fundamental functional programming concepts. I cannot stress how useful this resource was when learning F# and highly recommend it.

I also did several PluralSight courses on F#, which were also very handy to get started with F#.

> How did you tackle problems?

The usual mixture of trial and error, StackOverflow and blog posts. That said, F# is not a hugely popular language, so the amount of resources available was definitely a step back from what I was used to when doing C#.

> In what ways did F# differ from other languages you knew at the time?

To me, [units of measure](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/units-of-measure), [active patterns](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/active-patterns) and [type providers](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/type-providers/) were new concepts I hadn't seen.

> What was hard to learn?

I've tried to look into creating a type provider, but that was fairly involved.

> What concepts carried over nicely?

Virtually all of the functional programming staples: tuples, lists, pattern matching, sum types, type inference, function composition, etc. Also, the object-oriented features I knew also carried over nicely: classes, inheritance, mutation, etc.

> What did you struggle with?

I had to get to used to the fact that the ordering of my files matters. I was so used to just creating source files and letting the compiler figure things out. Having to be explicit about the order of files took a bit of getting used to (I love it now).

As F# is similar to Scala in that it supports object-oriented programming too, it was sometimes hard to decide when to use a functional approach vs an object-oriented approach. At first, having seen the functional programming light, I wrote everything in a functional way. However, after some time I realised that the two approaches are not actually mutually exclusive. There are cases where one approach works better than the other. There was also a nice presentation by Don Syme, F#'s creator, that he intended F# to be used in both a functional _and_ an object-oriented way (albeit functional-first though).

In C#, there is a convention that each file should have only one type. In F#, it is common for files to have multiple types. I had to learn when to group types in the same files; how to organise them.

Also, if you're working with built-in types (like `string`), some functionality can be accessed in both an object-oriented way (`str.Length`) or a functional way (`String.length str`). The former is always shorter, but is not functional. I found it hard to determine when to use which approach.

> What did you have to unlearn?

With my C# roots, creating a type is usually a bit of a hassle (there is much syntax/ceremony involved). In F#, there is far less syntax involved in creating types, and types are also a lot more expressive and powerful (this was also true in Haskell). I had to get used to creating many more types, even small wrapper types around primitive types (like `bool`).

In Haskell the pointfree style of composing functions is quite popular. In F#, this is less commonly used, and things are usually written in a slightly more verbose way.

> What syntax did you have to remap?

Not much. Haskell had prepared me for a semicolon-less, whitespace-significant syntax. One thing I did have to unmap was how to write lambda expressions (inline functions).

**Comment by MiyamotoAkira** [comment]
> How was your experience learning F#?
Interesting, to say the least. Had been doing exclusively C# for a while. I felt that I was starting to root. Did some python, but I wanted a bigger change on my way of thinking. There were quite a few eye openers.
 
> What was helpful while learning F#?
[FSharpForFunAndProfit](https://fsharpforfunandprofit.com/)

> What did you struggle with?
Immutability. That was the biggest change on what I have done before

> How did you tackle problems?
Perseverance? And the fact that I liked the language. Mostly going back to FSharpForFunAndProfit, and a bit of the official documentation (which continues to be quite awful)

> In what ways did F# differ from other languages you knew at the time?
First language I used that was FP. Oh and the indentation to indicate scope, which I love

> What was hard to learn?
Everything was Immutable. A recurrent theme in here, due to it being my first FP language.

> What did you have to unlearn?
Back to mutability, immutability. Trying to find new ways of doing the same exercises that I have done before on OOP languages.

> What syntax did you have to remap?
Map/Filter/Reduce. I have an idea of them due to LINQ, but the names where different,  and took me a bit to link them. Also, no parenthesis, no commas for function parameters. It throws you off because you can have partial application, and the order of resolution sometimes gives you strange errors.

>What concepts carried over nicely?
I have started to use a bit fluent style on OOP. So pipelines where easy to understand. In fact, I love them :-)
Also, concepts of Clean Code and SOLID do map quite nicely on FP.

**Comment by davidelettieri** [comment]
> How was your experience learning F#?

It was fun and challenging, I was amazed by type providers and since I was just discovering FP being able to use VS and the .NET Framework was a great motivation in choosing F# instead of another functional programming language.

> What was helpful while learning F#?

FSharpForFunAndProfit for sure, solving problems on Hackerrank and similar platforms

> What did you struggle with?

Coming from C# I was used to automatic conversion between number types while in F# you have to explicitly convert values and in general I was used to a looser type system. Syntax was very different, F# list correspond to an immutable singly-linked lists which is a data structure I didn't use in C# and has different performance and behavior with respect to IEnumerable data structures of C#

> How did you tackle problems?

Most of the times it was trial and error and reading through blog posts

> In what ways did F# differ from other languages you knew at the time?

I was working mainly with C# and F# type system was way more powerful, it has pattern matching, union types, record types, option types and F# has a more powerful type inference. F# also has a REPL which C# hadn't at the time. With F# everything is an expressions while in C# we have statements. 

> What was hard to learn?

Immutability, avoiding loops, if/else is a statement, the unit type

> What did you have to unlearn?

Loops that updates variables, using methods on objects, thinking about function arguments as something that is a "whole" and always required. 

> What syntax did you have to remap?

Testing equality with a single "=", writing lambda expressions

> What concepts carried over nicely?

I liked the fluent style of LINQ so the forward pipe operator was somewhat familiar and since C# had delegates and events I was also a bit used to thinking about function as values.

**Comment by martinfreedman** [comment]
**How was your experience learning F#?** 
Brilliant. I learnt F# to some degree a few years ago but then stopped. The change from v1 to v2 in exercism put me off using exercism then.  However revisiting a couple of months ago, much of what I liked from v1 is now back (except that great v1 logo). It is still is not social nor gamified enough though :-( Anyway I have been blasting through the exercises. It is particularly useful to see others solutions  and learn from them, although I have to admit that is happening less and less as I get to the more rarefied end of the track. :-( More I am mystified by others more complex solutions. but there is a lack of social to find if I am missing something.  My background being diverse but includes APL and J (and Fortran, SPlus, matlab, C,C++ etc.) and far more recently C# which I have long been writing in a functional fashion if possible, switching to F# felt like a duck to water. 

**What was helpful while learning F#?** 
Various blogs and books but as everyone else has noted [FSharpForFunAndProfit](https://fsharpforfunandprofit.com) is a brilliant resource. Also attending SkillsMatter and various youtube videos .e.g NDC talks.

**What did you struggle with?** 
Often poor documentation official or otherwise. Examples are the best source of learning to me. whcih is why I like seeing others solutions if I am struggling. (Although I use other sources first if I can) For example, I just used the Json TypeProvider but it took quite a while to iron out its quirks but if you see my code in [RestApi ](https://exercism.io/tracks/fsharp/exercises/rest-api/solutions/99afe4fb53444118bbdc0b0dc907de5f) it all looks so simple. _The main weakness of the exercism approach is not getting practice writing tests._

**How did you tackle problems?**
From first principles. If new then blogs and documents, if I have written it in C# then I check that solution - and immediately want to refactor that - as I have sometimes done after completing the F# solution. 

**In what ways did F# differ from other languages you knew at the time?** 
It was both similar and not to C# due tot the common .Net base. However you need very little of that to do the F# track. Loving Linq made it easy to adapt to F# collections (still not as good as APL/J but getting there). I like the space indention like python but needed to get used to the strict compiler control on formatting. 

**What was hard to learn?** 
A key challenge was understanding the type inference failure messages and how to deal with them. I love that this is to minimise type annotations which are an incredible pain in C# and nonexistent in J and Python (for different reasons)) . Type annotations is what put me off exploring F# and Haskell in the first place but now, certainly for F#, the goal,is to minimise their use, phew!

**What did you have to unlearn?** 
How much I relied on mutability and how pointless it is most of the time

**What syntax did you have to remap?** 
unary minus versus negation. F# should have used _1 instead of -1 like J. It is a minor pain. Not much else to be honest I have always hated {} C type language syntax.

**What concepts carried over nicely?**
LINQ from C#. Older collection concepts from J/APL/Matlab(ugh!) and SPlus (now R)

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our research for the v3 version of Exercism which has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

Thanks everyone for chipping in! It has been greatly appreciated.
